general-settings:
  name: Statusnook
mail-groups:
  core:
    name: Core
    members:
      - core1@example.com
      - core2@example.com
  engineers:
    name: Engineers
    description: All engineers in our organisation
    members:
      - engineer1@example.com
notification-channels:
  azure:
    from: example@example.com
    host: smtp.azurecomm.net
    name: Azure
    password: secret_Qg6RqkWLe1m4a6TzK+grCcgRIQsiFEc95nJXMsLBZIZSyA==.tOw0xDcUdmmr62tJ
    port: 587
    type: smtp
    username: example
  postmark:
    from: example@example.com
    host: smtp.postmarkapp.com
    misc:
      pm-broadcast: broadcast
      pm-transactional: outbound
    name: Postmark
    password: secret_hyNDZ3rL5ee7eco6DCoGnKcVsksZFY4MMb3b4JsCwbGh3A==.YwiY1DgH0ExUsDmJ
    port: 587
    type: smtp
    username: secret_hyNDZ3rL5ee7eco6DCoGnKcVsksZFY4MMb3b4JsCwbGh3A==.YwiY1DgH0ExUsDmJ
  ses:
    from: example@example.com
    host: email-smtp.eu-north-1.amazonaws.com
    name: SES
    password: secret_ZYjE7eePnHBlQph6pK0e30yeVpovb37h/VvcJbPw96fbHg==./1e5EXv1iUF8Y6XY
    port: 587
    type: smtp
    username: example
  slack-internal-alerts:
    name: "Slack #internal-alerts"
    type: slack
    webhook-url: https://hooks.slack.com/services/...
monitors:
  get:
    name: Example
    url: https://example.com
    method: GET
    frequency: 10
    timeout: 5
    attempts: 1
    notification-channels:
      - azure
      - postmark
  post-form:
    name: Post form example
    url: https://example.com
    method: POST
    frequency: 10
    timeout: 5
    attempts: 1
    headers:
      Content-Type: application/x-www-form-urlencoded
    body:
      example-name: example-value
    notification-channels:
      - ses
    mail-groups:
      - engineers
      - core
  post-json:
    name: Post json example
    url: https://example.com
    method: POST
    frequency: 10
    timeout: 5
    attempts: 1
    headers:
      Content-Type: application/json
    body: '{"key1": "value1", "key2": "value2"}'
    notification-channels:
      - azure
    mail-groups:
      - core
services:
  website:
    name: Website
    description: example.com
  api:
    name: API
    description: api.example.com
alert-notification-settings:
  email-notification-channel: postmark
  managed-subscriptions: true
  slack-client-secret: secret_tdBs7fxa31U+Nc31MUWBVea5pdT6ycHUsCOXfw==.M/qsy+BDnJoMALin
  slack-install-url: https://slack.com/oauth/v2/authorize?...
